version: '3'

services:
  szpnuw.portal:
    image: szpnuwportal
    build:
      context: .
      dockerfile: SZPNUW.Portal/Dockerfile

  szpnuw.webapi.account:
    image: szpnuwwebapiaccount
    build:
      context: .
      dockerfile: Microservices/SZPNUW.WebAPI.Account/Dockerfile

