version: '3'

services:
  szpnuw.portal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:80"

  szpnuw.webapi.account:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

