version: '3'

services:
  szpnuw.portal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name:
      "szpnuw.portal"
    ports:
      - "7001:7001"
    depends_on:
      - szpnuw.webapi.account.v3
      - szpnuw.webapi.subject.v3
      - szpnuw.webapi.sections.v3
      - szpnuw.webapi.projects.v3

  szpnuw.webapi.account.v3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7002:7002"

  szpnuw.webapi.subject.v3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7003:7003"

  szpnuw.webapi.sections.v3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7004:7004"

  szpnuw.webapi.projects.v3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7005:7005"
  
  szpnuw.proxy.v3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:80"

