version: '3'

services:
  szpnuw.portal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:80"
    depends_on:
      - szpnuw.webapi.account

  szpnuw.webapi.account:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7001:80"
