version: '3'

services:
  

  szpnuw.portal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7001:80"
    container_name:
      "szpnuw.portal"
    depends_on:
      - szpnuw.webapi.account
      - szpnuw.webapi.subject
      - szpnuw.webapi.sections
      - szpnuw.webapi.projects

  szpnuw.webapi.account:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7002:80"

  szpnuw.webapi.subject:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7003:80"

  szpnuw.webapi.sections:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7004:80"

  szpnuw.webapi.projects:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7005:80"
  
  szpnuw.proxy:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:80"

