version: '3'

services:
  szpnuw.portal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name:
      "szpnuw.portal"
    ports:
      - "7001:80"
    depends_on:
      - szpnuw.webapi.account.v3
      - szpnuw.webapi.subject.v3
      - szpnuw.webapi.sections.v3
      - szpnuw.webapi.projects.v3

  szpnuw.webapi.account.v3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7002:80"

  szpnuw.webapi.subject.v3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7003:80"

  szpnuw.webapi.sections.v3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7004:80"

  szpnuw.webapi.projects.v3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7005:80"
  
  szpnuw.proxy.v3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:80"

