version: '3'

services:   
  szpnuw.database.v2:
    image: szpnuwdatabasev2:latest
    restart: always
    build:
      context: .
      dockerfile: Database/Dockerfile
    ports:
       - 5433:5432
    environment:
         POSTGRES_PASSWORD: qwerty
    volumes:
       - pgdata:/var/lib/postgresql/data
    networks:
       - mynetwork

  szpnuw.portal:
    image: szpnuwportal:latest
    build:
      context: .
      dockerfile: SZPNUW.Portal/Dockerfile
    volumes:
       - pgdata:/var/lib/postgresql/data
    networks:
       - mynetwork

  szpnuw.webapi.account.v3:
    image: szpnuwwebapiaccount:latest
    build:
      context: .
      dockerfile: Microservices/SZPNUW.WebAPI.Account/Dockerfile
    links:
       - szpnuw.database.v2
    depends_on:
       - szpnuw.database.v2
    networks:
       - mynetwork

  szpnuw.webapi.subject.v3:
    image: szpnuwwebapisubject:latest
    build:
      context: .
      dockerfile: Microservices/SZPNUW.WebAPI.Subject/Dockerfile
    links:
       - szpnuw.database.v2
    depends_on:
       - szpnuw.database.v2
    networks:
       - mynetwork


  szpnuw.webapi.sections.v3:
    image: szpnuwwebapisections:latest
    build:
      context: .
      dockerfile: Microservices/SZPNUW.WebAPI.Sections/Dockerfile
    links:
       - szpnuw.database.v2
    depends_on:
       - szpnuw.database.v2
    networks:
       - mynetwork


  szpnuw.webapi.projects.v3:
    image: szpnuwwebapiprojects:latest
    build:
      context: .
      dockerfile: Microservices/SZPNUW.WebAPI.Projects/Dockerfile
    links:
       - szpnuw.database.v2
    depends_on:
       - szpnuw.database.v2
    networks:
       - mynetwork

  szpnuw.proxy.v3:
    image: szpnuwproxy:latest
    build:
      context: .
      dockerfile: ApiGw/APIGateway/Dockerfile
    networks:
       - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
     driver: bridge