---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "default1"
---
kind: Service
apiVersion: v1
metadata:
  name: szpnuwdatabase
  namespace: default
spec:
  selector:
    app: szpnuwdatabase
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 5
  labels:
    run: szpnuwdatabase
  name: szpnuwdatabase
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: szpnuwdatabase
      app: szpnuwdatabase
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: szpnuwdatabase
        app: szpnuwdatabase
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: qwerty
        image: gcr.io/szpnuw-project/database:v2
        imagePullPolicy: Always
        name: szpnuwdatabase
        ports:
        - containerPort: 5432
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdata
      nodeSelector:
        apptype: database
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: pgdata
---
apiVersion: v1
data:
  nginx1.conf: "events { worker_connections 4096; }\n\nhttp {\n\n\tupstream portal
    {\n\t\tserver portal1-1;\n\t}\n\tupstream account {\n\t\tserver account1-1;\n\t}\n\tupstream
    sections {\n\t\tserver sections1-1;\n\t}\n\tupstream subject {\n\t\tserver subject1-1;\n\t}\n\tupstream
    projects {\n\t\tserver projects1-1;\n\t}\n\t\n\tserver {\n\t\tlisten 80;\n\t\tlocation
    /Account {\n\t\t\tproxy_pass http://account;\n\t\t}\n\t\tlocation /SysLog {\n\t\t\tproxy_pass
    http://account;\n\t\t}\n\t\tlocation /Sections {\n\t\t\tproxy_pass http://sections;\n\t\t}\n\t\tlocation
    /Meeting {\n\t\t\tproxy_pass http://sections;\n\t\t}\n\t\tlocation /Report {\n\t\t\tproxy_pass
    http://sections;\n\t\t}\n\t\tlocation /Subject {\n\t\t\tproxy_pass http://subject;\n\t\t}\n\t\tlocation
    /Semester {\n\t\t\tproxy_pass http://subject;\n\t\t}\n\t\tlocation /Project {\n\t\t\tproxy_pass
    http://projects;\n\t\t}\n\t\tlocation / {\n\t\t\tproxy_pass http://portal;\n\t\t}\n\t}\n}\n\n"
kind: ConfigMap
metadata:
  name: nginx-config1
  namespace: default1
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "database-config1"
  namespace: "default1"
data:
  CONNECTION_STRING: "Host=szpnuwdatabase.default;Database=szpnuw;Username=user;Password=qwerty"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: portal1-1
  name: portal1-1
  namespace: default1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7001
  selector:
    app: portal1-1
  type: ClusterIP
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "portal1-1"
  namespace: "default1"
  labels:
    app: "portal1-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "portal1-1"
  template:
    metadata:
      labels:
        app: "portal1-1"
    spec:
      containers:
      - name: "portal"
        image: "gcr.io/szpnuw-project/portal:v2"
      nodeSelector:
        apptype: portal
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: account1-1
  name: account1-1
  namespace: default1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7002
  selector:
    app: account1-1
  type: ClusterIP
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "account1-1"
  namespace: "default1"
  labels:
    app: "account1-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "account1-1"
  template:
    metadata:
      labels:
        app: "account1-1"
    spec:
      containers:
      - name: "account"
        image: "gcr.io/szpnuw-project/account:v4"
        resources:
          requests:
             cpu: 400m
          limits:
             cpu: 420m
        env:
        - name: "CONNECTION_STRING"
          valueFrom:
            configMapKeyRef:
              key: "CONNECTION_STRING"
              name: "database-config1"
      nodeSelector:
        apptype: microservices
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "account1-1-hpa"
  namespace: "default1"
  labels:
    app: "account1-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "account1-1"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sections1-1
  name: sections1-1
  namespace: default1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7004
  selector:
    app: sections1-1
  type: ClusterIP
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "sections1-1"
  namespace: "default1"
  labels:
    app: "sections1-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "sections1-1"
  template:
    metadata:
      labels:
        app: "sections1-1"
    spec:
      containers:
      - name: "sections"
        image: "gcr.io/szpnuw-project/sections:v4"
        resources:
          requests:
             cpu: 400m
          limits:
             cpu: 420m
        env:
        - name: "CONNECTION_STRING"
          valueFrom:
            configMapKeyRef:
              key: "CONNECTION_STRING"
              name: "database-config1"
      nodeSelector:
        apptype: microservices
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "sections1-1-hpa"
  namespace: "default1"
  labels:
    app: "sections1-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "sections1-1"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: subject1-1
  name: subject1-1
  namespace: default1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7003
  selector:
    app: subject1-1
  type: ClusterIP
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "subject1-1"
  namespace: "default1"
  labels:
    app: "subject1-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "subject1-1"
  template:
    metadata:
      labels:
        app: "subject1-1"
    spec:
      containers:
      - name: "subject"
        image: "gcr.io/szpnuw-project/subject:v4"
        resources:
          requests:
             cpu: 400m
          limits:
             cpu: 420m
        env:
        - name: "CONNECTION_STRING"
          valueFrom:
            configMapKeyRef:
              key: "CONNECTION_STRING"
              name: "database-config1"
      nodeSelector:
        apptype: microservices
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "subject1-1-hpa"
  namespace: "default1"
  labels:
    app: "subject1-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "subject1-1"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: projects1-1
  name: projects1-1
  namespace: default1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7005
  selector:
    app: projects1-1
  type: ClusterIP
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "projects1-1"
  namespace: "default1"
  labels:
    app: "projects1-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "projects1-1"
  template:
    metadata:
      labels:
        app: "projects1-1"
    spec:
      containers:
      - name: "projects"
        image: "gcr.io/szpnuw-project/projects:v4"
        resources:
          requests:
             cpu: 400m
          limits:
             cpu: 420m
        env:
        - name: "CONNECTION_STRING"
          valueFrom:
            configMapKeyRef:
              key: "CONNECTION_STRING"
              name: "database-config1"
      nodeSelector:
        apptype: microservices
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "projects1-1-hpa"
  namespace: "default1"
  labels:
    app: "projects1-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "projects1-1"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-1
  name: nginx-1
  namespace: default1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-1
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "nginx-1"
  namespace: "default1"
  labels:
    app: "nginx-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nginx-1"
  template:
    metadata:
      labels:
        app: "nginx-1"
    spec:
      containers:
      - name: "nginx"
        image: "nginx:latest"
        resources:
          requests:
             cpu: 500m
          limits:
             cpu: 550m
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config1
          subPath: nginx1.conf
      volumes:
      - configMap:
          name: nginx-config1
        name: nginx-config1
      nodeSelector:
        apptype: nginx

